export const API = {
  STORAGE_PATH_SET: 1,

  MASTER_VAULT_INIT: 2,
  MASTER_VAULT_GET_STATUS: 3,
  MASTER_VAULT_GET: 4,
  MASTER_VAULT_CLOSE: 5,
  MASTER_VAULT_ADD: 6,
  MASTER_VAULT_LIST: 7,

  ACTIVE_VAULT_FILE_ADD: 8,
  ACTIVE_VAULT_FILE_REMOVE: 9,
  ACTIVE_VAULT_FILE_GET: 10,

  ACTIVE_VAULT_INIT: 11,
  ACTIVE_VAULT_GET_STATUS: 12,
  ACTIVE_VAULT_CLOSE: 13,
  ACTIVE_VAULT_ADD: 14,
  ACTIVE_VAULT_REMOVE: 15,
  ACTIVE_VAULT_LIST: 16,
  ACTIVE_VAULT_GET: 17,
  ACTIVE_VAULT_CREATE_INVITE: 18,
  ACTIVE_VAULT_DELETE_INVITE: 19,
  PAIR_ACTIVE_VAULT: 20,
  INIT_LISTENER: 21,
  ON_UPDATE: 22,
  ENCRYPTION_INIT: 23,
  ENCRYPTION_GET_STATUS: 24,
  ENCRYPTION_GET: 25,
  ENCRYPTION_ADD: 26,
  ENCRYPTION_CLOSE: 27,
  ENCRYPTION_HASH_PASSWORD: 28,
  ENCRYPTION_ENCRYPT_VAULT_KEY_WITH_HASHED_PASSWORD: 29,
  ENCRYPTION_ENCRYPT_VAULT_WITH_KEY: 30,
  ENCRYPTION_DECRYPT_VAULT_KEY: 31,
  ENCRYPTION_GET_DECRYPTION_KEY: 32,
  CLOSE_ALL_INSTANCES: 33,
  CANCEL_PAIR_ACTIVE_VAULT: 34,
  BLIND_MIRRORS_GET: 35,
  BLIND_MIRRORS_ADD: 36,
  BLIND_MIRROR_REMOVE: 37,
  BLIND_MIRRORS_ADD_DEFAULTS: 38,
  BLIND_MIRRORS_REMOVE_ALL: 39,
  MASTER_PASSWORD_STATUS: 40,
  RECORD_FAILED_MASTER_PASSWORD: 41,
  RESET_FAILED_ATTEMPTS: 42
}

export const API_BY_VALUE = Object.entries(API).reduce((acc, [key, value]) => {
  acc[value] = key
  return acc
}, {})
